-- Update LedgerReason enum values for BudgetLedger/CreditLedger
ALTER TABLE `BudgetLedger`
  MODIFY COLUMN `reason` ENUM(
    'MISSION_REWARD',
    'MISSION_APPROVED_CHARGE',
    'PAYOUT',
    'PAYOUT_REVERSAL',
    'TOPUP',
    'PRODUCT_ORDER_CREDIT',
    'PRODUCT_ORDER_BURN',
    'PRODUCT_ORDER_POINTS_BURN',
    'PRODUCT_ORDER_POINTS_REFUND',
    'REFUND',
    'ADJUSTMENT'
  ) NOT NULL;

ALTER TABLE `CreditLedger`
  MODIFY COLUMN `reason` ENUM(
    'MISSION_REWARD',
    'MISSION_APPROVED_CHARGE',
    'PAYOUT',
    'PAYOUT_REVERSAL',
    'TOPUP',
    'PRODUCT_ORDER_CREDIT',
    'PRODUCT_ORDER_BURN',
    'PRODUCT_ORDER_POINTS_BURN',
    'PRODUCT_ORDER_POINTS_REFUND',
    'REFUND',
    'ADJUSTMENT'
  ) NOT NULL;

